"""Add twitch info to user

Revision ID: b1f0e5f684fa
Revises: 601f74ad117e
Create Date: 2021-08-25 01:58:48.813668

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "b1f0e5f684fa"
down_revision = "601f74ad117e"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("twitch_auth_token", sa.String(), nullable=True))
    op.add_column(
        "users", sa.Column("twitch_refresh_token", sa.String(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "twitch_refresh_token")
    op.drop_column("users", "twitch_auth_token")
    # ### end Alembic commands ###
